version: '3'
services:
  doris_fe:
    image: apache/doris:1.2.2-fe-x86_64
    container_name: doris_fe
    restart: always
    volumes:
      - ./conf/fe.conf:/doris-fe/conf/fe.conf
      - ./log/fe:/doris-fe/log
    ports:
      - 8030:8030
      - 9030:9030
    environment:
      - CLUSTER_ID=doris-cluster
      - ROLE=fe
      - LOCAL_IP=fe_ip
      - HTTP_PORT=8030
      - HTTP_CHARSET=utf8
      - LOG_LEVEL=info
    networks:
      - ngdbp-network
    command: /bin/sh -c "cd /doris-fe/ && bin/start_fe.sh"

  doris_be:
    image: apache/doris:1.2.2-be-x86_64
    container_name: doris_be
    restart: always
    volumes:
      - ./conf/be:/doris/be/conf
      - ./log/be:/doris/be/log
      - ./data/be:/doris/be/data
    environment:
      - CLUSTER_ID=doris-cluster
      - ROLE=be
      - HTTP_PORT=8030
      - LOG_LEVEL=info
      - PULSAR_BROKER_SERVICE_URL=pulsar://pulsar_broker_ip:pulsar_broker_port
      - PULSAR_ADMIN_URL=http://pulsar_broker_ip:pulsar_admin_port
      - MASTER_IP=doris_fe_ip
    networks:
      - ngdbp-network
    command: /bin/sh -c "cd /doris/be/ && bin/start_be.sh"

  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    restart: always
    ports:
      - 8040:8040
      - 9000:9000
      - 9050:9050
    environment:
      - PULSAR_MEM=1g
    networks:
      - ngdbp-network
    command: /bin/sh -c "bin/pulsar standalone"


networks:
  ngdbp-network:
    driver: bridge